# Generated by Django 3.2.23 on 2024-02-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_type',
            new_name='name',
        ),
    ]
