# Generated by Django 3.2.23 on 2024-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdb', '0002_rename_program_type_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_attended', to='vdb.Program'),
        ),
    ]
