# Generated by Django 3.2.23 on 2024-02-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdb', '0004_auto_20240214_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cohort',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=50, null=True),
        ),
    ]
