# Generated by Django 3.2.23 on 2024-03-13 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vdb', '0006_auto_20240214_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('columns', models.TextField()),
                ('row', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='image',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
